/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TwoFactorRouteImport } from "./routes/two-factor"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as AcceptInviteRouteImport } from "./routes/accept-invite"
import { Route as AppRouteRouteImport } from "./routes/app/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AppIndexRouteImport } from "./routes/app/index"
import { Route as TTokenRouteImport } from "./routes/t.$token"
import { Route as AppSettingsRouteImport } from "./routes/app/settings"
import { Route as AppAdminRouteImport } from "./routes/app/admin"
import { Route as AppMMailboxIdRouteImport } from "./routes/app/m/$mailboxId"
import { Route as AppMMailboxIdIndexRouteImport } from "./routes/app/m/$mailboxId.index"
import { Route as AppMMailboxIdTThreadIdRouteImport } from "./routes/app/m/$mailboxId.t.$threadId"

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: "/two-factor",
  path: "/two-factor",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: "/accept-invite",
  path: "/accept-invite",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: "/t/$token",
  path: "/t/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMMailboxIdRoute = AppMMailboxIdRouteImport.update({
  id: "/m/$mailboxId",
  path: "/m/$mailboxId",
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMMailboxIdIndexRoute = AppMMailboxIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppMMailboxIdRoute,
} as any)
const AppMMailboxIdTThreadIdRoute = AppMMailboxIdTThreadIdRouteImport.update({
  id: "/t/$threadId",
  path: "/t/$threadId",
  getParentRoute: () => AppMMailboxIdRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/app": typeof AppRouteRouteWithChildren
  "/accept-invite": typeof AcceptInviteRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/two-factor": typeof TwoFactorRoute
  "/app/admin": typeof AppAdminRoute
  "/app/settings": typeof AppSettingsRoute
  "/t/$token": typeof TTokenRoute
  "/app/": typeof AppIndexRoute
  "/app/m/$mailboxId": typeof AppMMailboxIdRouteWithChildren
  "/app/m/$mailboxId/": typeof AppMMailboxIdIndexRoute
  "/app/m/$mailboxId/t/$threadId": typeof AppMMailboxIdTThreadIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accept-invite": typeof AcceptInviteRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/two-factor": typeof TwoFactorRoute
  "/app/admin": typeof AppAdminRoute
  "/app/settings": typeof AppSettingsRoute
  "/t/$token": typeof TTokenRoute
  "/app": typeof AppIndexRoute
  "/app/m/$mailboxId": typeof AppMMailboxIdIndexRoute
  "/app/m/$mailboxId/t/$threadId": typeof AppMMailboxIdTThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/app": typeof AppRouteRouteWithChildren
  "/accept-invite": typeof AcceptInviteRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/reset-password": typeof ResetPasswordRoute
  "/two-factor": typeof TwoFactorRoute
  "/app/admin": typeof AppAdminRoute
  "/app/settings": typeof AppSettingsRoute
  "/t/$token": typeof TTokenRoute
  "/app/": typeof AppIndexRoute
  "/app/m/$mailboxId": typeof AppMMailboxIdRouteWithChildren
  "/app/m/$mailboxId/": typeof AppMMailboxIdIndexRoute
  "/app/m/$mailboxId/t/$threadId": typeof AppMMailboxIdTThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/app"
    | "/accept-invite"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/two-factor"
    | "/app/admin"
    | "/app/settings"
    | "/t/$token"
    | "/app/"
    | "/app/m/$mailboxId"
    | "/app/m/$mailboxId/"
    | "/app/m/$mailboxId/t/$threadId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accept-invite"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/two-factor"
    | "/app/admin"
    | "/app/settings"
    | "/t/$token"
    | "/app"
    | "/app/m/$mailboxId"
    | "/app/m/$mailboxId/t/$threadId"
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/accept-invite"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/two-factor"
    | "/app/admin"
    | "/app/settings"
    | "/t/$token"
    | "/app/"
    | "/app/m/$mailboxId"
    | "/app/m/$mailboxId/"
    | "/app/m/$mailboxId/t/$threadId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TwoFactorRoute: typeof TwoFactorRoute
  TTokenRoute: typeof TTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/two-factor": {
      id: "/two-factor"
      path: "/two-factor"
      fullPath: "/two-factor"
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accept-invite": {
      id: "/accept-invite"
      path: "/accept-invite"
      fullPath: "/accept-invite"
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/": {
      id: "/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/t/$token": {
      id: "/t/$token"
      path: "/t/$token"
      fullPath: "/t/$token"
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/settings": {
      id: "/app/settings"
      path: "/settings"
      fullPath: "/app/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/admin": {
      id: "/app/admin"
      path: "/admin"
      fullPath: "/app/admin"
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/m/$mailboxId": {
      id: "/app/m/$mailboxId"
      path: "/m/$mailboxId"
      fullPath: "/app/m/$mailboxId"
      preLoaderRoute: typeof AppMMailboxIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    "/app/m/$mailboxId/": {
      id: "/app/m/$mailboxId/"
      path: "/"
      fullPath: "/app/m/$mailboxId/"
      preLoaderRoute: typeof AppMMailboxIdIndexRouteImport
      parentRoute: typeof AppMMailboxIdRoute
    }
    "/app/m/$mailboxId/t/$threadId": {
      id: "/app/m/$mailboxId/t/$threadId"
      path: "/t/$threadId"
      fullPath: "/app/m/$mailboxId/t/$threadId"
      preLoaderRoute: typeof AppMMailboxIdTThreadIdRouteImport
      parentRoute: typeof AppMMailboxIdRoute
    }
  }
}

interface AppMMailboxIdRouteChildren {
  AppMMailboxIdIndexRoute: typeof AppMMailboxIdIndexRoute
  AppMMailboxIdTThreadIdRoute: typeof AppMMailboxIdTThreadIdRoute
}

const AppMMailboxIdRouteChildren: AppMMailboxIdRouteChildren = {
  AppMMailboxIdIndexRoute: AppMMailboxIdIndexRoute,
  AppMMailboxIdTThreadIdRoute: AppMMailboxIdTThreadIdRoute,
}

const AppMMailboxIdRouteWithChildren = AppMMailboxIdRoute._addFileChildren(
  AppMMailboxIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMMailboxIdRoute: typeof AppMMailboxIdRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppMMailboxIdRoute: AppMMailboxIdRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TwoFactorRoute: TwoFactorRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
